// AUTH REDUCERS
export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const LOAD_USER = 'LOAD_USER';
export const LOG_OUT = 'LOG_OUT';
export const STOP_INITIAL_LOADER = 'STOP_INITIAL_LOADER';
export const USER_DEV_PROFILE_CREATE = 'USER_DEV_PROFILE_CREATE';
export const AUTH_ERROR = 'AUTH_ERROR';

// USER PROFILE Handle Reducers
export const FETCH_DASHBOARD = 'FETCH_DASHBOARD';
export const GET_DEV_PROFILE = 'GET_DEV_PROFILE';
export const USER_PROFILE_LOADING_START = 'USER_PROFILE_LOADING_START';
export const CLEAR_USER_PROFILE = 'CLEAR_USER_PROFILE';
export const DEV_PROFILE_CHANGE = 'DEV_PROFILE_CHANGE';
export const ADD_NEW_CREDITS = 'ADD_NEW_CREDITS';
export const REMOVE_EDUCATION = 'REMOVE_EDUCATION';
export const REMOVE_EXPERIENCE = 'REMOVE_EXPERIENCE';

// ALerts
export const ADD_ALERTS = 'ADD_ALERTS';
export const CLOSE_ALERT = 'CLOSE_ALERT';
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

// Posts
export const POST_LOADING = 'POST_LOADING';
export const FETCH_POSTS = 'FETCH_POSTS';
export const ADD_POST = 'ADD_POST';
export const POST_REACTION = 'POST_REACTION';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const GET_SINGLE_POST = 'GET_SINGLE_POST';
export const SINGLE_POST_LOADER = 'SINGLE_POST_LOADER';
export const CLEAR_POST_STATE = 'CLEAR_POST_STATE';

// Developers
export const FETCH_DEVELOPERS = 'FETCH_DEVELOPERS';
export const DEVELOPERS_LOADER = 'DEVELOPERS_LOADER';
export const DEVELOPER_PROFILE_LOADER = 'DEVELOPER_PROFILE_LOADER';
export const FETCH_DEVELOPER_PROFILE = 'FETCH_DEVELOPER_PROFILE';
