-- CREATE TABLE IF NOT EXISTS USERS (
--     ID INT PRIMARY KEY AUTO_INCREMENT,
--     NAME VARCHAR(100) NOT NULL,
--     EMAIL_ADDRESS VARCHAR(100) NOT NULL UNIQUE,
--     EMAIL_VERIFIED BOOL DEFAULT FALSE,
--     PASSWORD VARCHAR(255) NOT NULL,
--     CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
--     UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );
-- ALTER TABLE USERS
--     ADD COLUMN EMAIL_VERIFIED BOOL DEFAULT FALSE;
    
-- ALTER TABLE USERS 
--     MODIFY EMAIL_ADDRESS VARCHAR(100) NOT NULL UNIQUE;

ALTER TABLE USERS
    ADD COLUMN USERNAME VARCHAR(100) UNIQUE;
    